FROM debian
ADD debian.list /etc/apt/sources.list.d/
RUN apt-get update && apt-get -y upgrade && apt -y install nginx && apt-get clean && \
    cd /var/www/ && rm -rf ./* && \
    mkdir -p orangejuiz.com/img && \
    chmod -R 754 /var/www/orangejuiz.com/ && \
    useradd Max && groupadd Pad && usermod -aG Pad Max && \
    chown -R Max:Pad /var/www/orangejuiz.com/ && \
    sed -i 's/\/var\/www\/html/\/var\/www\/orangejuiz.com/g' /etc/nginx/sites-enabled/default && \
    sed -i 's/user www-data/user Max/g' /etc/nginx/nginx.conf
ADD index.html /var/www/orangejuiz.com/
ADD img.jpg /var/www/orangejuiz.com/img/
CMD ["nginx", "-g", "daemon off;"]
